name: CI Pipeline  # Название пайплайна

on:  # События, запускающие пайплайн
  push:
    branches:
      - main  # Запуск при пуше в ветку master
  pull_request:
    branches:
      - main  # Запуск при создании PR в master

jobs:  # Задачи пайплайна
  build:  # Название задачи (сборка)
    runs-on: ubuntu-latest  # ОС для выполнения

    steps:  # Шаги выполнения
      - name: Checkout code  # Клонирование репозитория
        uses: actions/checkout@v3

      - name: Setup Node.js  # Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Версия Node.js (подходит для большинства Vite-проектов)

      - name: Install dependencies  # Установка зависимостей
        run: npm install

      - name: Build project  # Сборка проекта
        run: npm run build

      - name: Test (optional)  # Проверка работоспособности
        run: npm run preview -- --port 8080 || echo "No tests defined"